
# ----- Tilting Laser -----
tilt_laser:
  laser_cb_detector_config:  /none

  configs:
  - config_name: small_cb_4x5
    laser_cb_detector:
      active: True
      num_x: 6
      num_y: 8
      width_scaling: 1
      height_scaling: 1
      subpixel_window: 4
      subpixel_zero_zone: 1
      flip_horizontal: 1

tilt_laser_8x6:
  laser_cb_detector_config:  /none
  configs: []

tilt_laser_7x6:
  laser_cb_detector_config:  /none
  configs: []
